# Use the new Container based KVM stack which allows "sudo" access
dist: trusty

language: cpp

compile:
  - clang

sudo: required

only:
  - master

services:
    - docker

install:
  # Install all of the dependencies
  - git submodule update --init
  - sudo apt-get install -y libc++

script:
  - make

after_success:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t munnerz/ps3netsrv:${TRAVIS_COMMIT:0:7} .
  - docker tag -f munnerz/ps3netsrv:${TRAVIS_COMMIT:0:7} "munnerz/ps3netsrv:latest"
  - docker push munnerz/ps3netsrv:latest
  - docker push munnerz/ps3netsrv:${TRAVIS_COMMIT:0:7}
